// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BodyHeightController from "./body_height_controller"
application.register("body-height", BodyHeightController)

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import EventTimeFormatController from "./event_time_format_controller"
application.register("event-time-format", EventTimeFormatController)

import SwitchModeController from "./switch_mode_controller"
application.register("switch-mode", SwitchModeController)
